version: "3.9"
services:
  pollution-monitor:
    build: .
    ports:
      - "9002:9002"
  database:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "pollution_monitor"
    ports:
      - "7002:5432"

